In [6]:
#Creating Arrays
import numpy as np
marks=np.array([10,20,30,40,50])
print(marks) #no commans

[10 20 30 40 50]


In [11]:
#python List vs Array

marks=[10,20,30,40,50]
new_marks=[]
for i in marks:
    new_marks.append(i+5)
print(new_marks)
arr=np.array([10,20,30,40,50])
print(arr+5)

[15, 25, 35, 45, 55]
[15 25 35 45 55]


In [19]:
#indexing same as python list
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

10
50


In [20]:
#slicing same as python list
arr=np.array([10,20,30,40,50])
print(arr[0:3])

[10 20 30]


In [23]:
#Vectorized operations
arr=np.array([10,20,30,40,50])
print(arr+1)
print(arr-2)
print(arr*3)
print("Constantly used in analytics")

[11 21 31 41 51]
[ 8 18 28 38 48]
[ 30  60  90 120 150]
Constantly used in analytics


In [26]:
#Statistics
arr=np.array([10,20,30,40,50])
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))

30.0
50
10
150


In [30]:
#Mini Challenge
import numpy as np
scores = np.array([70, 80, 90, 60, 100])
#1. Add 10 marks to everyone
print(scores+10)

#2.Find Average
print(np.mean(scores))

#3.Find highest score
print(np.max(scores))

#4.Find lowest score
print(np.min(scores))

[ 80  90 100  70 110]
80.0
100
60


In [31]:
#2D-Array
marks=np.array([
    [70,80],
    [90,85],
    [60,75]
])
print(marks)

[[70 80]
 [90 85]
 [60 75]]


In [33]:
#accessing elements
marks=np.array([
    [70,80],
    [90,85],
    [60,75]
])
print(marks[0][1])
print(marks[1][1])

80
85


In [35]:
#shape
print(marks.shape)#indicates the (number of rows, number of columns)

(3, 2)


In [38]:
#column selection
print(marks[:,0])
print(marks[:,1])

[70 90 60]
[80 85 75]


In [42]:
#avg of one subjects
math_marks=marks[:,0]
print(np.mean(math_marks))

73.33333333333333


In [51]:
#challenge 2
data=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(data.shape)
print(data[:,1])

(3, 3)
[20 50 80]


In [72]:
#coding task
sales=np.array([
    [100,120],
    [150,170],
    [200,250]
])
jan_sales=sales[:,0]
feb_sales=sales[:,1]
print(np.mean(jan_sales))
print(np.mean(feb_sales))
print(np.max(sales))
print(sales.shape)
jan_sales=sales[:,0]
print(np.mean(jan_sales))

150.0
180.0
250
(3, 2)
150.0


In [55]:
#Reshaping
arr=np.array([1,2,3,45,6])
print(arr.shape)
#reshape is used when you want to represent a array in 2-D
arr=np.array([1,2,3,4,5,6])
new_arr=arr.reshape(3,2)#how many (rows, col)
print(new_arr)#rule to remind while reshaping array row*col==number of array elements

(5,)
[[1 2]
 [3 4]
 [5 6]]


In [56]:
#challenge3
arr=np.array([10,20,30,40,50,60])
new_arr=arr.reshape(2,3)
print(new_arr)
print(new_arr.shape)

[[10 20 30]
 [40 50 60]]
(2, 3)


In [59]:
import numpy as np
data = np.array([5,10,15,20,25,30,35,40])
reshaped_data=data.reshape(4,2)
print(reshaped_data)
print(reshaped_data.shape)
second_col=reshaped_data[:,1]
print(second_col)
print(np.mean(second_col))


[[ 5 10]
 [15 20]
 [25 30]
 [35 40]]
(4, 2)
[10 20 30 40]
25.0


In [61]:
#Matrix Operation
#Addition & Multiplication
A=np.array([
    [1,2],
    [3,4]
])
B=np.array([
    [5,6],
    [7,8]
])
print(A+B)
print(A*B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [62]:
#Analytics example
sales=np.array([100,200,300])
bouns_sales=sales*1.10
print(bouns_sales)

[110. 220. 330.]


In [63]:
#Random data generation
data=np.random.randint(1,101,size=10)
print(data)

[90 26 83  6 70 38 13 55 73 66]


In [64]:
#matrix using randome func()
mat=np.random.randint(1,102,size=(3,3))
print(mat)

[[ 4 24 27]
 [69 82 79]
 [ 5 33  1]]


In [68]:
#coding task
marks=np.random.randint(50,101,size=(5,3))
print(marks)
print(marks.shape)
science_marks=marks[:,1]
print(np.mean(science_marks))
print(np.max(marks))
print(np.min(marks))

[[65 92 87]
 [98 53 98]
 [83 99 80]
 [53 80 58]
 [83 75 73]]
(5, 3)
79.8
99
53


In [69]:
#challenge4
A=np.array([10,20,30])
print(A*2+5)

[25 45 65]
