In [6]:
import numpy as np
marks = np.array([
    [70,80,90],
    [60,85,95],
    [90,75,88]
])
print(marks)
#before using axis
sci_marks=marks[:,1]
print(np.sum(sci_marks))

[[70 80 90]
 [60 85 95]
 [90 75 88]]
240


In [9]:
#axis=0(column wise)Sum
print(np.sum(marks,axis=0)) #70+60+80

[220 240 273]


In [10]:
#axis=1(row wise)sum
print(np.sum(marks,axis=1))#70+80+90

[240 240 253]


In [13]:
#mean with aixs
print(np.mean(marks,axis=0))#col wise
print(np.mean(marks,axis=1))#row wise

[73.33333333 80.         91.        ]
[80.         80.         84.33333333]


In [14]:
#maximum with axis
print(np.max(marks,axis=0))
print(np.max(marks,axis=1))

[90 85 95]
[90 95 90]


In [17]:
#challenge1
data=np.array([
    [10,20,30],
    [40,50,60]
])
print(np.sum(data,axis=0))
print(np.sum(data,axis=1))

[50 70 90]
[ 60 150]


In [22]:
#Matrix Tanspose
arr=np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.shape)
t_arr=arr.T
print(t_arr)
print(t_arr.shape)

(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [24]:
#challenge 2
arr=np.array([
    [10,20],
    [30,40],
    [50,60]
])
print(arr.shape)
print(arr.T.shape)
print(arr.T)

(3, 2)
(2, 3)
[[10 30 50]
 [20 40 60]]


In [32]:
#Analytics example
sales=np.array([
    [100,120,130],#month->col,  store->row
    [150,170,180],
    [200,220,250]
])
#sales per month
print(np.sum(sales,axis=0))
#sales per store
print(np.sum(sales,axis=1))

[450 510 560]
[350 500 670]


In [33]:
#coding Task
sales=np.array([
    [100,200,300],
    [150,250,350],
    [200,300,400]
])
#1.print shape
print(sales.shape)

#2.Print Tanspose
print(sales.T)

#3.Total sales per month
print(np.sum(sales,axis=0))

#4.Total sales per sotre
print(np.sum(sales,axis=1))

#5.Average sales per month

print(np.mean(sales,axis=0))

#6.highest sles in each month

print(np.max(sales,axis=0))

(3, 3)
[[100 150 200]
 [200 250 300]
 [300 350 400]]
[ 450  750 1050]
[600 750 900]
[150. 250. 350.]
[200 300 400]


In [36]:
#Filtering
import numpy as np
marks=np.array([45,67,89,32,95])
#Find students who passed (>50)
print(marks>50) #called as boolean mask

[False  True  True False  True]


In [38]:
print(marks[marks>50])#filtering the students who scored above 50

[67 89 95]


In [39]:
#example
sales=np.array([100,250,180,300,120])
print(sales[sales>150])

[250 180 300]


In [46]:
#Coding challenge
import numpy as np
scores = np.array([55, 80, 45, 90, 70, 30])

#1.all scores greater than 60

print(scores[scores>60])

#2. Print all scores less than 50.

print(scores[scores<50])

#3.Find the average of scores greater than 60.

print(np.mean(scores[scores>60]))

#4.Find the highest score among scores greater than 60

print(np.max(scores[scores>60]))

[80 90 70]
[45 30]
80.0
90


In [47]:
#challenge 3
scores = np.array([10,20,30,40,50])

print(scores[scores >= 30])

[30 40 50]
