In [16]:
#Boardcasting
import numpy as np
marks = np.array([70, 80, 90])
#add five to each element
print(marks+5)#boardcasting [70+5 85+5 90+5]

[75 85 95]


In [15]:
#Analytics example
#Suppose GST increased by 18%.
sales=np.array([1000, 2000, 3000])
print(sales*1.8)#sales with 18% gst

[1800. 3600. 5400.]


In [5]:
#Challenge 1
arr = np.array([10,20,30])

print(arr * 3)

[30 60 90]


In [13]:
#Boardcasting between array
A=np.array([10,20,30])
B=np.array([1,2,3])
print(A+B) #A+B=[10+1 20+2 30+3]

[11 22 33]


In [17]:
#When Broadcasting Fails
A=np.array([10,20,30])
B=np.array([1,2])
print(A+B) #while broadcasting we have to ensure that array contains same number of rows and col

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [20]:
#Advanced Filtering
#AND condition
#Print all scores greater than 50. and less than 90 
scores=np.array([40,55,70,85,95])
#same as normal filtering but contians logical operations
print(scores[(scores>50)&(scores<90)])#conditions inside ()

[55 70 85]


In [23]:
#OR condition
#Print all scores less than 50. or greater than 90 
print(scores[(scores<50)|(scores>90)])

[40 95]


In [24]:
#analytics example
marks=np.array([45,67,89,32,95,78])
print(marks[marks>=75])

[89 95 78]


In [25]:
#challenge 2
scores = np.array([20,40,60,80,100])

print(scores[(scores >= 40) & (scores <= 80)])

[40 60 80]


In [27]:
#Normal Multiplication
#Element-wise multiplicaton
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

print(A * B)##[[1*5 2*6]
                ##[3*7 4*8]]

[[ 5 12]
 [21 32]]


In [33]:
#Matrix Multiplication
print(A@B)

[[19 22]
 [43 50]]


In [2]:
#Mini Project
#Student Performance Analyzer
import numpy as np

marks = np.array([
    [78,85,90],
    [65,70,68],
    [92,88,95],
    [55,60,58],
    [80,75,85]
])#col->math,science,english & row->students

#Task1(Find average marks for each subject.)

print(np.mean(marks,axis=0))

#Task2(Find total marks for each student.)

print(np.sum(marks,axis=1))

#Task3(Find the topper's total marks.)

print(np.max(np.sum(marks,axis=1)))

#Task4(Find students whose average marks are above 80.)

student_averages=np.mean(marks, axis=1)
print(student_averages[student_averages>80])

[74.  75.6 79.2]
[253 203 275 173 240]
275
[84.33333333 91.66666667]


In [42]:
#Prediction Question
arr=np.array([5,10,15])
print(arr+2)

[ 7 12 17]
