In [2]:
#np.where()
#yesterddays task
import numpy as np
student_averages = np.array([84.3, 67.6, 91.6, 57.6, 80.0])

print(student_averages[student_averages > 80])

[84.3 91.6]


In [3]:
#But if we have to return index 
#Then we use np.where()

print(np.where(student_averages>80))#0,2 cause indxing starts from 0

(array([0, 2]),)


In [5]:
scores=np.array([40,70,90,55,95])
print(np.where(scores>80))

(array([2, 4]),)


In [6]:
#Sorting
sales=np.array([500,200,900,100])

#Sort Asecending
print(np.sort(sales))

[100 200 500 900]


In [9]:
#Sort Descending
print(np.sort(sales)[::-1])#slicing Day1 of numpy (slicing->(start:Stop:step)step[-1]last ele

[900 500 200 100]


In [ ]:
#Analysts use sort to track the top slaes or least slaes 

In [10]:
#challenge 2
arr=np.array([8,3,1,6])
print(np.sort(arr))

[1 3 6 8]


In [13]:
#Unique Values
cities=np.array([
    "Mangalore",
    "Bangalore",
    "Mangalore",
    "Mysore",
    "Bangalore"
])
print(cities)

#if we want to print unique vaules we use np.unique()
print(np.unique(cities))#cleanner

['Mangalore' 'Bangalore' 'Mangalore' 'Mysore' 'Bangalore']
['Bangalore' 'Mangalore' 'Mysore']


In [14]:
cities=[
    "Mangalore",
    "Bangalore",
    "Mangalore",
    "Mysore",
    "Bangalore"
]
print(np.unique(cities))#works for all

['Bangalore' 'Mangalore' 'Mysore']


In [15]:
#Challenge 3
nums=np.array([1,1,2,2,3,3,3])
print(np.unique(nums))

[1 2 3]


In [17]:
#Missing Vaules Basics #imp
marks=np.array([
    80,
    90,
    np.nan,#missing value
    75,
    88
])
print(np.mean(marks))#output is missing value

nan


In [18]:
#to overcom missing vaule error use 
#nanmean()
print(np.nanmean(marks))#ignores missing values

83.25


In [ ]:
#Why This Matters
#In analytics:
#Missing data is everywhere.
#People skip forms.
#Sensors fail.
#Data gets corrupted.

In [31]:
#Final Mini Project 
#Student Analytics System

import numpy as np

marks = np.array([
    [78,85,90],
    [65,70,68],
    [92,88,95],
    [55,60,58],
    [80,75,85],
    [92,88,95]
])#col->math,science,english & row->students

#Task1(Find average marks per subject.)

print(np.mean(marks,axis=0))

#Task2(Find topper total marks.)

print(np.max(np.sum(marks,axis=1)))

#Task3(Find student indexes whose average > 80.)

print(np.where(np.mean(marks,axis=1)>80))

#Task4(Find highest score in each subject.)

print(np.max(marks,axis=0))

#Task5(Sort in descending)

totals = np.sum(marks,axis=1)
print(totals)#default order
print(np.sort(totals)[::-1])#desecending order

#Task6(Find all unique total scores.)

print(np.unique(np.sum(marks,axis=1)))

[77.         77.66666667 81.83333333]
275
(array([0, 2, 5]),)
[92 88 95]
[253 203 275 173 240 275]
[275 275 253 240 203 173]
[173 203 240 253 275]


In [29]:
#prediction question

arr = np.array([10,20,30,40])

print(np.where(arr >= 30))

(array([2, 3]),)
